branches:
  - main
tagFormat: v${version}
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - breaking: true
          release: major
        - type: feat
          release: minor
        - type: fix
          release: patch
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/github"
    - assets:
        - path: dist/ClipChop-*.dmg
        - path: dist/ClipChop-*.deb
        - path: dist/ClipChop-*.rpm
        - path: dist/ClipChop-*.AppImage
        - path: dist/ClipChop-*.exe
        - path: dist/ClipChop-*.msi
